# Generated by Django 3.1.7 on 2021-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train_inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('link', models.CharField(max_length=350, verbose_name='Ссылка')),
                ('city_iz', models.CharField(max_length=20, verbose_name='Город отправления')),
                ('vokzal_iz', models.CharField(max_length=20, verbose_name='Вокзал отправления')),
                ('time_iz', models.CharField(max_length=10, verbose_name='Время отправления')),
                ('date_iz', models.DateField(verbose_name='Дата отправления')),
                ('city_v', models.CharField(max_length=20, verbose_name='Город прибытия')),
                ('vokzal_v', models.CharField(max_length=20, verbose_name='Вокзал прибытия')),
                ('time_v', models.CharField(max_length=10, verbose_name='Время прибытия')),
                ('date_v', models.DateField(verbose_name='Дата прибытия')),
                ('price_1', models.FloatField(verbose_name='Плацкарт')),
                ('price_2', models.FloatField(verbose_name='Купе')),
                ('price_3', models.FloatField(verbose_name='СВ')),
                ('price_4', models.FloatField(default=0, verbose_name='Цена4')),
                ('price_5', models.FloatField(default=0, verbose_name='Цена5')),
            ],
        ),
    ]
