# Generated by Django 3.1.7 on 2021-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findconf', '0003_avia_info_hotel_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField(verbose_name='ID города')),
                ('city_name', models.CharField(max_length=35, verbose_name='Название города')),
                ('city_country_id', models.PositiveIntegerField(verbose_name='ID страны города')),
            ],
        ),
        migrations.CreateModel(
            name='country_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.PositiveIntegerField(verbose_name='ID страны')),
                ('country_name', models.CharField(max_length=35, verbose_name='Название страны')),
            ],
        ),
    ]
