# Generated by Django 3.1.7 on 2021-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findconf', '0004_city_info_country_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
    ]
