# Generated by Django 3.1.7 on 2021-05-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findconf', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='train_inf',
        ),
    ]
